name: qbittorrent-arnatious # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: qbittorrent
summary: A free and lightweight torrent client
description: |
  qBittorrent is a full featured FOSS alternative to uTorrent.

  With a lightweight, Qt based GUI and built in search engine,
  Bittorrent extensions, and advanced network management tools,
  qBittorrent is the best client available.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures: [amd64, arm64]

parts:
  qbittorrent:
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://github.com/qbittorrent/qBittorrent.git
    source-branch: v4_6_x
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_EXE_LINKER_FLAGS_RELEASE=-s
      - -DCMAKE_INSTALL_PREFIX=''
    override-pull: |
      craftctl default
      craftctl set "version=$(git describe | sed 's/^release-//')"
    override-build: |
      craftctl default
      sed 's|^Icon=.*|Icon=${SNAP}/share/icons/hicolor/scalable/apps/qbittorrent.svg|' \
        -i "$CRAFT_PART_INSTALL/share/applications/org.qbittorrent.qBittorrent.desktop"
    build-packages:
      - zlib1g-dev
      - libssl-dev
    prime:
      - bin
      - share/applications
      - share/icons/hicolor/scalable/apps
    after:
      - libtorrent

  libtorrent:
    plugin: cmake
    build-packages:
      - build-essential
      - libboost-dev
      - libssl-dev
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=''
      - -DBUILD_SHARED_LIBS=OFF
    source: https://github.com/arvidn/libtorrent.git
    source-branch: RC_1_2
    prime:
      - -*

apps:
  qbittorrent:
    extensions:
      - kde-neon
    command: bin/qbittorrent
    desktop: share/applications/org.qbittorrent.qBittorrent.desktop
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - raw-usb
      - unity7
      - gsettings
      - network-status
      - network-manager
      - network-control

plugs:
  desktop:
    mount-host-font-cache: false
