name: qbittorrent-arnatious # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
adopt-info: qbittorrent
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  qbittorrent:
    # See 'snapcraft plugins'
    plugin: cmake
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    source: https://github.com/qbittorrent/qBittorrent.git
    source-branch: v4_2_x
    parse-info:
      - usr/share/metainfo/org.qbittorrent.qBittorrent.appdata.xml
    build-packages:
      - libtool
      - git
      - zlib1g-dev
      - libboost-dev
      - libboost-system-dev
      - libboost-chrono-dev
      - libboost-random-dev
      - libssl-dev
      - libgeoip-dev
      - pkg-config
      - libglvnd-dev
    build-snaps:
      - cmake
      - kde-frameworks-5-core18
      - kde-frameworks-5-core18-sdk
    stage-packages:
      - python3
      - libcanberra-gtk3-module
      - freeglut3
      - libgpm2
      - libslang2
      - libboost-system-dev
    after:
      - libtorrent

  libtorrent:
    plugin: cmake
    build-packages:
      - build-essential
      - libboost-dev
      - libboost-system-dev
      - libboost-chrono-dev
      - libboost-random-dev
      - libssl-dev
    build-snaps:
      - cmake
    source: https://github.com/arvidn/libtorrent.git
    source-branch: RC_1_2
    stage-packages:
      - libboost-system1.65.1

  cleanup:
    after:  # Make this part run last; list all your other parts here
      - qbittorrent
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core18
      - cmake
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
    override-prime: |
      set -eux
      for snap in "core18" "cmake" "kde-frameworks-5-core18-sdk" "kde-frameworks-5-core18"; do  # List all content-snaps and base snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

apps:
  qbittorrent:
    command: usr/bin/qbittorrent
    extensions:
      - kde-neon
    common-id: org.qbittorrent.qBittorrent
    plugs:
      - x11
      - home
      - network
      - network-bind
      - removable-media
      - raw-usb
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - gsettings
      - network-status
      - network-manager
      - network-control
      - opengl
      - kde-frameworks-5-plug

slots:
  session-dbus-interface:
    interface: dbus
    name: org.qbittorrent.qBittorrent
    bus: session
