name: qbittorrent-arnatious # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
adopt-info: qbittorrent
summary: A free and lightweight torrent client
description: |
  qBittorrent is a full featured FOSS alternative to uTorrent.

  With a lightweight, Qt based GUI and built in search engine,
  Bittorrent extensions, and advanced network management tools,
  qBittorrent is the best client available.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on:
    - arm64
    - amd64

parts:
  qbittorrent:
    # See 'snapcraft plugins'
    plugin: autotools
    source: https://github.com/qbittorrent/qBittorrent.git
    source-branch: v4_4_x
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe)
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=qbittorrent|Icon=/usr/share/icons/hicolor/192x192/apps/qbittorrent.png|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/org.qbittorrent.qBittorrent.desktop
    build-snaps:
      - kde-frameworks-5-qt-5-15-3-core20-sdk/latest/candidate
    build-packages:
      - libtool
      - git
      - zlib1g-dev
      - libboost-dev
      - libboost-system-dev
      - libboost-chrono-dev
      - libboost-random-dev
      - libssl-dev
      - libgeoip-dev
      - pkg-config
    stage-snaps:
      - kde-frameworks-5-qt-5-15-3-core20-sdk/latest/candidate
      - kde-frameworks-5-qt-5-15-3-core20/latest/candidate
    stage-packages:
      - python3
      - libcanberra-gtk3-module
    after:
      - libtorrent
      - kde-neon-extension
    build-environment: &id001
      - SNAPCRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current
      - PKG_CONFIG_PATH: /snap/kde-frameworks-5-qt-5-15-3-core20-sdk/6/usr/lib/x86_64-linux-gnu/pkgconfig

  libtorrent:
    plugin: cmake
    build-packages:
      - build-essential
    cmake-parameters:
      - -DCMAKE_CXX_STANDARD=14
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=''
    source: https://github.com/arvidn/libtorrent.git
    source-branch: RC_1_2
    stage-packages:
      - libboost-system-dev

  kde-neon-extension:
    build-packages:
    - g++    
    build-snaps:
    - kde-frameworks-5-qt-5-15-3-core20-sdk/latest/candidate
    make-parameters:
    - PLATFORM_PLUG=kde-frameworks-5-plug
    plugin: make
    source: $SNAPCRAFT_EXTENSIONS_DIR/desktop
    source-subdir: kde-neon
    
layout:
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
apps:
  qbittorrent:
    adapter: full
    command: usr/bin/qbittorrent
    command-chain:
      - snap/command-chain/desktop-launch
    desktop: usr/share/applications/org.qbittorrent.qBittorrent.desktop
    plugs:
      - x11
      - home
      - network
      - network-bind
      - removable-media
      - raw-usb
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - gsettings
      - network-status
      - network-manager
      - network-control
      - opengl
    environment:
      DISABLE_WAYLAND: 1
      QT_QPA_PLATFORMTHEME: gtk3

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gsettings: null
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  desktop:
    mount-host-font-cache: false
  kde-frameworks-5-plug:
    content: kde-frameworks-5-qt-5-15-3-core20-all
    default-provider: kde-frameworks-5-qt-5-15-3-core20
    interface: content
    target: $SNAP/kf5
  kde-frameworks-5-qt-5-15-3-core20:
    content: kde-frameworks-5-qt-5-15-3-core20-all
    default-provider: kde-frameworks-5-qt-5-15-3-core20
    interface: content
    target: $SNAP/kf5
assumes:
  - snapd2.43
environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/kf5
hooks:
  configure:
    command-chain:
    - snap/command-chain/hooks-configure-desktop
    plugs:
    - desktop
