on:
  push:
    branches:
      - master
      - github-actions
  schedule:
    - cron: "0 0 * * 2"

jobs:
  build:
    uses: arnatious/qbittorrent-arnatious/.github/workflows/build-snap@github-actions
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: snap
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
